EvotecIT/OfficeIMO

OfficeIMO.Tests/Word.Save.cs, OfficeIMO.Word/WordDocument.cs
- OpenXmlPackage's now kept in MemoryStream and Cloned on Save.
- Fixed typo in Test_Save unit test.
- Added CopyPackageProperties() because Open-XML-SDK doesn't do this automatically on Clone or SaveAs [(see issue #1150)](https://github.com/OfficeDev/Open-XML-SDK/issues/1150)
=> Fixed SaveAs functionality

CHANGELOG.MD, OfficeIMO.Tests/Word.Sections.cs, OfficeIMO.Word/WordPageSizes.cs
This PR fixes a problem when you set PageOrientation before setting PageSize. In case that happens it always revert back to `Portrait`
=> FIxes PageOrientation when mixed with PageSize

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create02.cs, OfficeIMO.Tests/Word.Breaks.cs, OfficeIMO.Tests/Word.Validation.cs, OfficeIMO.Word/WordBreak.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordHeaderFooter.Properties.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordParagraph.Run.cs, OfficeIMO.Word/WordParagraph.cs, OfficeIMO.Word/WordSection.cs
Should solve 
- https://github.com/EvotecIT/OfficeIMO/issues/37
```csharp
public static void Example_BasicWordWithBreaks(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with paragraph & breaks");
string filePath = System.IO.Path.Combine(folderPath, "BasicDocumentWithParagraphsAndBreaks.docx");
var paragraph1 = document.AddParagraph("Adding paragraph1 with some text and pressing ENTER");
var paragraph2 = document.AddParagraph("Adding paragraph2 with some text and pressing SHIFT+ENTER");
paragraph2.AddBreak();
paragraph2.AddText("Continue1");
paragraph2.AddBreak();
paragraph2.AddText("Continue2");
var paragraph3 = document.AddParagraph("Adding paragraph3 with some text and pressing ENTER"); …
```
=> Adds AddBreak() method to Paragraphs

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Tables/Tables.NestedTables1.cs, OfficeIMO.Tests/Word.TablesNested.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordSection.cs, OfficeIMO.Word/WordTable.Properties.cs, OfficeIMO.Word/WordTable.cs, OfficeIMO.Word/WordTableCell.cs
- Adds ability to add nested table into existing table.  
```csharp
internal static void Example_NestedTables(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with nested tables");
string filePath = System.IO.Path.Combine(folderPath, "Document with Nested Tables.docx");
var paragraph = document.AddParagraph("Lets add table ");
paragraph.ParagraphAlignment = JustificationValues.Center;
paragraph.Bold = true;
paragraph.Underline = UnderlineValues.DotDash;
WordTable wordTable = document.AddTable(4, 4, WordTableStyle.GridTable1LightAccent1);
wordTable.Rows[0].Cells[0].Paragraphs[0].Text = "Test 1";
wordTable.Rows[1].Cells[0].Paragraphs[0].Text = "Test 2"; …
```
=> Add ability to add nested tables (add table into cell of an existing table)

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create03.cs, OfficeIMO.Tests/Word.Settings.cs, OfficeIMO.Word/WordDocument.Parts.cs, OfficeIMO.Word/WordSettings.cs
This PR will address:
- https://github.com/EvotecIT/OfficeIMO/issues/45
- New fields added to WordSettings: FontSize, FontSizeComplexScript, FontFamily
```csharp
public static void Example_BasicWordWithDefaultStyleChange(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with different default style");
string filePath = System.IO.Path.Combine(folderPath, "BasicWordWithDefaultStyleChange.docx");
document.Settings.FontSize = 30;
document.Settings.FontFamily = "Calibri Light";
document.Settings.Language = "pl-PL";
var paragraph1 = document.AddParagraph("To jest po polsku");
var paragraph2 = document.AddParagraph("Adding paragraph1 with some text and pressing ENTER");
paragraph2.FontSize = 15; …
```
=> Allow to set default font, size, and other settings for the whole document

.editorconfig, OfficeIMO.Tests/Word.Save.cs
These changes are only aimed at making assert messages more readable. The use of var was also affected
=> Refactoring tests Word.Save

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create03.cs, OfficeIMO.Tests/Word.Settings.cs, OfficeIMO.Word/WordSettings.cs
Fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/54
Adds:
- FontFamilyHighAnsi for document.Settings which is required for special chars 
```csharp
public static void Example_BasicWordWithDefaultFontChange(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with different default style (PT/BR)");
string filePath = System.IO.Path.Combine(folderPath, "BasicWordWithDefaultStyleChangeBR.docx");
document.Settings.FontSize = 30;
//document.Settings.FontSizeComplexScript = 30;
document.Settings.FontFamily = "Calibri Light";
document.Settings.FontFamilyHighAnsi = "Calibri Light";
document.Settings.Language = "pt-Br";
string title = "INSTRUMENTO PARTICULAR DE CONSTITUIÇÃO DE GARANTIA DE ALIENAÇÃO …
```
=> Improve settings for document with PT-BR and HighAnsi chars

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create03.cs, OfficeIMO.Tests/Word.Settings.cs, OfficeIMO.Word/WordCompatibilitySettings.cs, OfficeIMO.Word/WordDocument.Parts.cs, OfficeIMO.Word/WordDocument.cs
This change fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/57
- Adds default settings, including compatibility settings, math properties, and few other things that are automatically added when Microsoft Word creates a document
- Adds default web settings that are the same to what Microsoft Word does
Sample of usage for compatiblity mode
```csharp
ublic static void Example_BasicWordWithDefaultFontChange(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with different default style (PT/BR)");
string filePath = System.IO.Path.Combine(folderPath, "BasicWordWithDefaultStyleChangeBR.docx");
document.Settings.FontSize = 30;
//document.Settings.FontSizeComplexScript = 30; …
```
=> Add Compatibility Mode, set default compatibility to highest version

OfficeIMO.Word/WordDocument.cs
Fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/65
During saving, the error should be meaningful. In this case, if the document is read-only, you can't save it.
=> Detect readonly before saving

OfficeIMO.Tests/Word.Bookmarks.cs, OfficeIMO.Word/WordBookmark.cs
Fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/66
Don't nessecary create run, if it's not there, as it isn't needed. 
Add test to make sure it doesn't throw
=> Skip creation of run, which isn't needed

OfficeIMO.Tests/Word.Lists.cs, OfficeIMO.Word/WordList.cs
Fix `IsToc` check when `"Heading"` exists with more than 1 character ending
P.S. I can remove the refactoring commit
Hide whitespaces will help watch diff
<details>
</details>
=> Fix check IsToc for Word.Lists

OfficeIMO.Examples/OfficeIMO.Examples.csproj, OfficeIMO.Excel/OfficeIMO.Excel.csproj, OfficeIMO.Tests/OfficeIMO.Tests.csproj, OfficeIMO.Word/OfficeIMO.Word.csproj
This PR closes #77 
I could to the testing on MacOS for VSC and VS:
My environment:
```
❯ dotnet sdk check
.NET SDKs:
Version      Status
----------------------------------------
5.0.408      .NET 5.0 is out of support.
6.0.403      Up to date.
7.0.100      Up to date.
.NET Runtimes:
Name                          Version      Status
----------------------------------------------------------------------
Microsoft.AspNetCore.App      5.0.17       .NET 5.0 is out of support.
Microsoft.NETCore.App         5.0.17       .NET 5.0 is out of support.
Microsoft.AspNetCore.App      6.0.11       Up to date.
Microsoft.NETCore.App         6.0.11       Up to date.
Microsoft.AspNetCore.App      7.0.0        Up to date.
Microsoft.NETCore.App         7.0.0        Up to date.
```
@PrzemyslawKlys could you …
=> Provide multi platform project config

OfficeIMO.Word/WordList.cs
Resolves an issue with
- #82 
The order within paragraph does matter. Paragraph properties needs to go first, and then run. If the order is not done properly things fail quietly
=> The order of paragraph properties and runs does matter

OfficeIMO.Tests/Word.Borders.cs, OfficeIMO.Tests/Word.Fields.cs, OfficeIMO.Tests/Word.Hyperlinks.cs, OfficeIMO.Tests/Word.Lists.cs, OfficeIMO.Tests/Word.Margins.cs, OfficeIMO.Tests/Word.PageSettings.cs, OfficeIMO.Tests/Word.Save.cs, OfficeIMO.Tests/Word.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordHyperLink.cs
This PR solves:
- As part of one PR, we found that the order of elements matters and we didn't notice it during the PR assessment. This PR adds a check right after document saving if there are any unexpected child elements. This should temporary work as an easy way to detect problems. In the long run `document.ValidationErrors should be 0`, but so far we have some issues to solve first
- changes order of elements in Hyperlink for Color, adds missing Value
- Add method `ValidateDocument()` with ability to define file format. Default is Microsoft365.
=> Improve tests, fix HyperLink order, add method ValidateDocument()

OfficeIMO.Examples/Word/HyperLinksAndFields/HyperLinks.BasicExample.cs, OfficeIMO.Examples/Word/HyperLinksAndFields/HyperLinks.EasyExample.cs, OfficeIMO.Word/WordHyperLink.cs
Fixes HyperLink AddStyle not being applied, with proper order of RunProperties for Validation to pass.
=> Fixes HyperLink AddStyle not being applied

OfficeIMO.Examples/Word/HyperLinksAndFields/HyperLinks.BasicExample.cs, OfficeIMO.Tests/Word.Hyperlinks.cs, OfficeIMO.Word/WordHyperLink.cs, OfficeIMO.Word/WordParagraph.PrivateMethods.cs, OfficeIMO.Word/WordParagraph.RunProperties.cs
This PR aims to resolve
- #90 
Hyperlinks are a bit like Paragraphs. This means that they have their own Runs, Texts and RunProperties. This PR tries to address this. When users interacts with WordParagraph and the properties such as Bold, Italic (and so on) are applied, and the WordParagraph contains a HyperLink the style will be applied to Hyperlink instead of applying it to a new Run that would not have any impact on styling. 
```cs
internal static void Example_BasicWordWithHyperLinks(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with hyperlinks");
string filePath = System.IO.Path.Combine(folderPath, "BasicDocumentHyperlinks.docx");
document.AddParagraph("Test 1"); …
```
=> Allows applying custom styling to Hyperlinks

OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordSection.cs
I wasn't able to use this lib due to this exception being thrown. I've noticed a similar exception in the code base was commented out, so my quick 'fix' was to do the same here.
=> remote exception from wordsection

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/CleanupDocuments/Cleanup.Sample01.cs, OfficeIMO.Examples/Word/LoadDocuments/LoadDocuments.Sample1.cs, OfficeIMO.Tests/Word.Cleanup.cs, OfficeIMO.Word/WordDocument.PrivateMethods.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs
This PR adds CleanupDocument() method so one can apply the cleaning up of existing or new documents. Microsoft Word, when you add bold, change color or similar will create separate runs to keep text. This is expected and something that keeps documents nicely formatted. However Microsoft Word for unknown reasons also sometimes adds new Runs that have very same formatting. I guess it could be user changed their mind when it comes to formatting and what was bold now isn't bold anymore.
For example: This is **very** long **line** **of** **text** - that would most likely translate into 7 runs in Microsoft Word OpenXml. So even tho the text line of text is BOLD all the way, it would treat it as 3 separate Runs. While this is ok, most of the time, it becomes really complicated when trying to …
=> Adds CleanupDocument method to merge same formatted runs

OfficeIMO.Examples/Word/Paragraphs/Paragraphs.BasicExample.cs, OfficeIMO.Tests/Word.Breaks.cs, OfficeIMO.Word/WordParagraph.RunProperties.cs
Fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/113
Adds tests:
- for Color (null)
- for Break (TextWrapping)
=> Fixes Color to return Null instead throw an error

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Paragraphs/Paragraphs.BasicTabStops.cs, OfficeIMO.Tests/Word.Paragraphs.cs, OfficeIMO.Tests/Word.TabStops.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordParagraph.cs, OfficeIMO.Word/WordSettings.cs, OfficeIMO.Word/WordTab.cs
This PR:
- Adds the ability to Add TabStops
- Adds the ability to modify DefaulTabStops
- Adds the ability to modify CharacterSpacingControl
- Adds the ability to modify existing tab stops
- Should resolve https://github.com/EvotecIT/OfficeIMO/issues/89
```cs
internal static void Example_BasicTabStops(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with paragraphs");
string filePath = System.IO.Path.Combine(folderPath, "Basic Document with some tab stops.docx");
var paragraph = document.AddParagraph("\tFirst Line");
document.Settings.DefaultTabStop = 2880;
document.Settings.CharacterSpacingControl = CharacterSpacingValues.DoNotCompress;
Console.WriteLine("Tabs count: " + …
```
=> Add Tab Stops to Word Paragraphs

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.CreateFontFamily.cs, OfficeIMO.Tests/Word.Paragraphs.cs, OfficeIMO.Tests/Word.Settings.cs, OfficeIMO.Word/WordParagraph.RunProperties.cs, OfficeIMO.Word/WordSettings.cs
This PR addresses:
- https://github.com/EvotecIT/OfficeIMO/issues/124
In the begining of OfficeIMO we only supported FontFamily as part of `Document.Settings.FontFamily` and `Paragraph.FontFamily`. The thing is there are 3 other settings in FontFamily. Those are HighAnsi, ComplexScript and EastAsia. I've added `FontFamilyHighAnsi` to global settings as a separate option, but forgot to add it for Paragraph. While I could just add HighAnsi to Paragraph I believe this is not enough to address issue. 
Most languages such as Polish have special chars. If we set FontFamily to Arial and we use mix of standard chars and special chars łążćźż it would only change FontFamily for standard chars and leave special chars on it's defaults. This makes no sense to treat special chars differently from my …
=> [Possibly breaking change] Set HighAnsi, EastAsia and ComplexScript at the same time as FontFamily

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Tabs.cs, OfficeIMO.Tests/Word.Tabs.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordParagraph.cs, OfficeIMO.Word/WordSection.cs, OfficeIMO.Word/WordTabChar.cs, OfficeIMO.Word/WordTabStop.cs
This PR solves:
- https://github.com/EvotecIT/OfficeIMO/issues/126
Add ability to add tabs to the document. 
```cs
public static void Example_BasicWordWithTabs(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with tabs");
string filePath = System.IO.Path.Combine(folderPath, "BasicWordWithTabs.docx");
var paragraph1 = document.AddParagraph("To jest po polsku").AddTab().AddTab().AddText("Test");
Console.WriteLine(document.Paragraphs.Count);
Console.WriteLine(document.Paragraphs[1].IsTabChar);
Console.WriteLine(document.Paragraphs[2].IsTabChar);
Console.WriteLine(paragraph1.IsTabChar);
var paragraph2 = document.AddParagraph("Adding paragraph1 with some text and pressing ENTER").AddTab(); …
```
=> Add support for Tabs

OfficeIMO.Word/OfficeIMO.Word.csproj
This PR downgrades:
- Downgrades DocumentFormat.OpenXml to 2.16.0 to be inline with ClosedXML (according to ClosedXML author there is a bug in 2.19
- Adds System.IO.Packaging 6.0.0
=> Downgrade DocumentFormat.OpenXml

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.CreateNewLines.cs, OfficeIMO.Tests/Word.BreaksNewLine.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordParagraph.PrivateMethods.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs
This PR adds the ability to create line breaks using `\n`, `\r\n` or `Environment.NewLine`
```cs
var test = document.AddParagraph("TestMe").AddText("\nFirst line\r\nAnd more " + Environment.NewLine + "in new line\r\n");
```
Is exactly the same as using it in explicit way:
```cs
var  test = document.AddParagraph("TestMe").AddBreak().AddText("First line").AddBreak().AddText("And more ").AddBreak().AddText("in new line").AddBreak();
```
Keep in mind that doing `document.Paragraphs[0].Text = "\nFirst line\r\nAnd more " + Environment.NewLine + "in new line\r\n");` doesn't do anything for the Breaks(). I believe that using Text property on paragraph explicitly that would create multiple WordParagraphs from a simple `Set` should not do that. 
Full example:
```cs
public static void …
```
=> Add ability to use NewLines ("\r\n"/Environment.NewLine) in AddParagraph, AddText

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.CreateLineSpacing.cs, OfficeIMO.Tests/Word.LineSpacing.cs, OfficeIMO.Word/WordParagraph.ParagraphProperties.cs
This PR fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/146
It also adds:
- an example for line spacing
- basic testing for line spacing
=> Fix for Incorrectly setting the LineSpacingRule property for paragraph

OfficeIMO.Tests/Word.TablesBeforeAfter.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs
This PR resolves:
- https://github.com/EvotecIT/OfficeIMO/issues/96
- Adds ability to use AddTableAfter without WordTableStyle
- Adds ability to use AddTableBefore without WordTableStyle
```cs
public WordTable AddTableAfter(int rows, int columns, WordTableStyle tableStyle = WordTableStyle.TableGrid)
public WordTable AddTableBefore(int rows, int columns, WordTableStyle tableStyle = WordTableStyle.TableGrid)
```
=> Add missing tests for AddTableAfter() and AddTableBefore() 

OfficeIMO.Examples/Word/FindAndReplace/FindAndReplace01.cs, OfficeIMO.Tests/Word.FindAndReplace.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordPositionInParagraph.cs, OfficeIMO.Word/WordTextSegment.cs
Till now, Office IMo can's find and replace the string from mutil para.  after search the web .found two source to do it
[Search and Replace Text in an Open XML WordprocessingML Document | Eric White](http://www.ericwhite.com/blog/search-and-replace-text-in-an-open-xml-wordprocessingml-document/)
https://github.com/nissl-lab/npoi/blob/32435d9485181a08f6993d3e94c10a70e5bb810a/ooxml/XWPF/Usermodel/XWPFParagraph.cs#L1307C22-L1307C22
the import thing is found the string location index of paras.
Also modify the wrong test and examples.
**Before**
**After**
=> implements muti para search and replace

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Images/ImageFixedPosition.cs, OfficeIMO.Tests/Word.Images.cs, OfficeIMO.Word/WordImage.cs
This PR adds a feature
* #164 
This is one by exposing positioning properties of the Image
```csharp
/// <summary>
/// Get or set the Image's horizontal position.
/// </summary>
public HorizontalPosition horizontalPosition {
get {
if (_Image.Inline == null) {
var anchor = _Image.Anchor;
var hPosition = anchor.HorizontalPosition;
return hPosition;
} else {
throw new InvalidOperationException("Inline images do not have HorizontalPosition property.");
}
}
set {
if (_Image.Inline == null) {
var anchor = _Image.Anchor;
anchor.HorizontalPosition = value;
} else {
throw new InvalidOperationException("Inline images do not have HorizontalPosition property.");
}
}
}
/// <summary>
/// Get or set the Image's vertical position.
/// </summary>
public VerticalPosition verticalPosition {
get {
if …
```
=> Fixed pos image

OfficeIMO.Tests/Word.Tables.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs
we have the full doc replace ,and sometimes ,we will want just replace from a list paras(indeed it was a real paragraph).so I pulic the  FindAndReplace method
```cs
public static  int  FindAndReplace(List<WordParagraph> paragraphs, string textToFind, string textToReplace, StringComparison stringComparison = StringComparison.OrdinalIgnoreCase)
```
=> pullic FindAndReplace

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Watermark/Watermark.Sample1.cs, OfficeIMO.Examples/Word/Watermark/Watermark.Sample3.cs, OfficeIMO.Tests/Word.Watermark.cs, OfficeIMO.Word/ColorNameResolver.cs, OfficeIMO.Word/ExtensionsHeadersAndFooters.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordFooter.cs, OfficeIMO.Word/WordHeader.cs, OfficeIMO.Word/WordHeaderFooter.Properties.cs, OfficeIMO.Word/WordSection.PrivateMethods.cs, OfficeIMO.Word/WordSection.PublicMethods.cs, OfficeIMO.Word/WordSection.cs, OfficeIMO.Word/WordWatermark.cs
Solves:
- https://github.com/EvotecIT/OfficeIMO/issues/138
- https://github.com/EvotecIT/OfficeIMO/issues/119
This change adds:
- Ability to modify watermark (colors, text, rotation, width, height)
- Ability to remove watermark
- Ability to find watermarks in document, sections, headers
- Ability to add watermark to document/section which makes watermark show up only on single page
- Ability to add watermark to headers/footers which makes watermark show up on whole section
**Breaking changes**
- This change breaks how watermarks are added. If you add them directly within section/document it will only apply to single page/pages as the SdtBlock gets added to body directly. If you need watermark for the whole section/document you need to add watermark to header/footer for it to apply to …
=> *BREAKING CHANGE* Improve Watermark with colors, rotation and other settings

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample3.cs, OfficeIMO.Word/WordHeader.cs, OfficeIMO.Word/WordHeaderFooter.Methods.cs, OfficeIMO.Word/WordTextBox.cs
Addreses some of the issues:
- https://github.com/EvotecIT/OfficeIMO/issues/185
=> Add basic method to add textbox to header/footer

CHANGELOG.MD, OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Images/Images.Sample1.cs, OfficeIMO.Examples/Word/Images/Images.Sample4.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample4.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample5.cs, OfficeIMO.Tests/Word.Images.cs, OfficeIMO.Tests/Word.TextBox.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordHeader.cs, OfficeIMO.Word/WordImage.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordSection.PublicMethods.cs, OfficeIMO.Word/WordTextBox.cs, OfficeIMO.Word/WordWrapTextImage.cs
This PR adds the following features:
- Use Paragraph instead of StdBlock (so that text within a TextBox is no "variable" anymore)
- Allow changing the insets of the TextBox so that there is no gap between the text of the TextBox and its border
- Allow the TextBox to be set to "AutoFitText" or not
- Allow the text to be multiline by respecting the page breaks
- Added Wrapping functionality including inline
- Added ability to convert inline to other wrapping types and vice versa (keep in mind that some properties are lost then or go to their defaults)
- Fixes wrong paragraph being returned when AddImage is used
Breaking change:
- Changes `WrapTextImage.InFrontText` to `WrapTextImage.InFrontOfText` to match Word naming
=> [WordTextBox] Add additional features

OfficeIMO.Tests/Word.Tables.cs, OfficeIMO.Word/WordTableCell.cs
Working with this library, I was having each cell being with an empty paragraph default styling. This pull request adds an optional parameter to the function for adding a paragraph, if left out or false the behavior will not change. When true the method will now remove every paragraph under the table cell. I had also considered making the parameter toggle deleting the prior paragraph only. This may be better, I decided against proposing that because a full reset is easier to think through in my mind.
The comment about mentioning in the PR ought to be removed, I have also documented the return value, parameter, and new parameter in the documentation comment.
This PR is untested.
=> Added the ability to clear the default empty paragraph in TableCell.

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create05.cs, OfficeIMO.Examples/Word/BasicDocument/BasicDocument.Create06.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample1.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample6.cs, OfficeIMO.Tests/Word.Margins.cs, OfficeIMO.Tests/Word.TextBox.cs, OfficeIMO.Word/Helpers.cs, OfficeIMO.Word/WordMargins.cs, OfficeIMO.Word/WordTextBox.cs, OfficeImo.sln.DotSettings
- Allow conversion for margins from Centimeters to Emus and back;
```cs
public static void Example_BasicWordWithMarginsInCentimeters(string folderPath, bool openWord) {
Console.WriteLine("[*] Creating standard document with margins");
string filePath = System.IO.Path.Combine(folderPath, "EmptyDocumentWithMarginsCentimeters.docx");
document.Sections[0].Margins.BottomCentimeters = 2.30;
document.Sections[0].Margins.TopCentimeters = 5.50;
document.Sections[0].Margins.LeftCentimeters = 3.01;
document.Sections[0].Margins.RightCentimeters = 3.05;
Console.WriteLine(document.Sections[0].Margins.BottomCentimeters);
Console.WriteLine(document.Sections[0].Margins.TopCentimeters); …
```
=> Add centimeters conversions to Margins, fix naming emus/twips

OfficeIMO.Examples/Word/Lists/Lists.Create1.cs, OfficeIMO.Examples/Word/Lists/Lists.Create7.cs, OfficeIMO.Examples/Word/Lists/Lists.Create8.cs, OfficeIMO.Tests/Word.Lists.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordHeaderFooter.Methods.cs, OfficeIMO.Word/WordList.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordTableCell.cs
Resolve issues described in:
- #204 
- #201 
Basically no longer allows to use `WordList wordList3 = document.AddList(WordListStyle.Headings111, true);` or using `RestartNumbering = true` as each list restarts by itself
=> **Breaking Change** - Remove continue & restart numbering from Lists 

OfficeIMO.Examples/Word/Lists/Lists.Create1.cs, OfficeIMO.Examples/Word/Lists/Lists.Create7.cs, OfficeIMO.Examples/Word/Lists/Lists.Create8.cs, OfficeIMO.Tests/Word.Lists.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordHeaderFooter.Methods.cs, OfficeIMO.Word/WordList.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordTableCell.cs
This PR resolves issue:
- https://github.com/EvotecIT/OfficeIMO/issues/206
This PR adds:
- Merging `document.Lists[0].Merge(document.Lists[1]);`
- Removal `document.Lists[0].Remove();`
How to use:
```cs
internal static void Example_BasicLists3(string folderPath, bool openWord) {
string filePath = System.IO.Path.Combine(folderPath, "Document with Lists3.docx");
var paragraph = document.AddParagraph("This is 1st list");
paragraph.ParagraphAlignment = JustificationValues.Center;
WordList wordList1 = document.AddList(WordListStyle.Headings111);
wordList1.AddItem("Text 1 - List1");
wordList1.AddItem("Text 2 - List1", 1);
wordList1.AddItem("Text 3 - List1", 2);
paragraph = document.AddParagraph("This is 2nd list"); …
```
=> Add Remove & Merge Lists

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample1.cs, OfficeIMO.Examples/Word/WordTextBox/WordTextBox.Sample2.cs, OfficeIMO.Tests/Word.TextBox.cs, OfficeIMO.Word/WordTextBox.cs
This PR solves:
- #224 
There are **Breaking Changes**:
- Removed `Text` property
- Removed `WordParagraph` property
- Added `Paragraphs` property, allowing for full manipulation
```cs
var textBox = document.AddTextBox("[Grab your reader’s attention with a great quote from the document or use this space to emphasize a key point. To place this text box anywhere on the page, just drag it.]");
Console.WriteLine("TextBox Text: " + textBox.Paragraphs[0].Text);
textBox.Paragraphs[0].Text = "We can then modify the text box text";
Console.WriteLine("TextBox Text: " + textBox.Paragraphs[0].Text);
Console.WriteLine("TextBoc Color: " + textBox.Paragraphs[0].Color.ToString());
textBox.Paragraphs[0].Text = "This is a text box 1";
Console.WriteLine("TextBox Text: " + textBox.Paragraphs[0].Text);
```
=> Improve textboxes to allow multiple Runs/Paragraphs **Breaking Changes**

OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Tables/Tables.Create4.cs, OfficeIMO.Tests/Word.Tables.cs, OfficeIMO.Word/WordTable.cs, OfficeIMO.Word/WordTableRow.cs
This PR resolves:
- https://github.com/EvotecIT/OfficeIMO/issues/230
```cs
WordTable wordTable = document.AddTable(4, 4, WordTableStyle.TableNormal);
wordTable.RepeatHeaderRowAtTheTopOfEachPage = true;
wordTable.Rows[0].Cells[0].Paragraphs[0].Text = "Test 1";
wordTable.Rows[1].Cells[0].Paragraphs[0].Text = "Test 2";
wordTable.Rows[2].Cells[0].Paragraphs[0].Text = "Test 3";
wordTable.Rows[3].Cells[0].Paragraphs[0].Text = "Test 4";
```
=> Add RepeatHeaderRowAtTheTopOfEachPage to Tables

OfficeIMO.Examples/OfficeIMO.Examples.csproj, OfficeIMO.Examples/Program.cs, OfficeIMO.Examples/Word/Embed/EmbedFragmentHTML.cs, OfficeIMO.Tests/OfficeIMO.Tests.csproj, OfficeIMO.Tests/Word.EmbeddedDocuments.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordEmbeddedDocument.cs
This PR resolves:
- https://github.com/EvotecIT/OfficeIMO/issues/228
The following example shows the use case. Remember that opening and closing <HTML> tags are necessary; otherwise, Microsoft Word won't open the file.
```cs
var htmlContent = """
<html lang="en">
<P>This is a paragraph.</P>
<P>This is another paragraph.</P>
<P>This is a paragraph with <STRONG>bold</STRONG> text.</P>
<P>This is a paragraph with <EM>italic</EM> text.</P>
<ul>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
<ol>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ol>
<P>This is a paragraph with a <A href=""https://www.google.com"">link</A>.</P>
</html>
""";
document.AddEmbeddedFragment(htmlContent, AlternativeFormatImportPartType.Html);
```
=> Add AddEmbeddedFragment method

OfficeIMO.Excel/OfficeIMO.Excel.csproj, OfficeIMO.VerifyTests/OfficeIMO.VerifyTests.csproj, OfficeIMO.Word/ImportTableStyle.cs, OfficeIMO.Word/OfficeIMO.Word.csproj, OfficeIMO.Word/WordDocument.cs
This PR adds:
- Bump OpenXMLSDK to 2.20
- Fixes require code to run
- Add missing tests for NET 7.0 in VerifyTests
=> Bump OpenXMLSDK to 2.20

OfficeIMO.Excel/OfficeIMO.Excel.csproj, OfficeIMO.Tests/OfficeIMO.Tests.csproj, OfficeIMO.VerifyTests/OfficeIMO.VerifyTests.csproj, OfficeIMO.Word/OfficeIMO.Word.csproj, azure-pipelines-linux.yml, azure-pipelines-macos.yml, azure-pipelines.yml
This PR:
- bumps SixLabors to higher version
- removes net 6.0, net 7.0 and netstandard 2.1
- adds 9.0
=> Bump dependencies / frameworks

.github/dependabot.yml
This pull request includes a configuration file for Dependabot to automate dependency updates. The most important change is the addition of the `.github/dependabot.yml` file to specify the package ecosystems to update and the location of the package manifests.
Configuration for Dependabot:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R11): Added configuration file to specify package ecosystems, directory location of package manifests, and update schedule.
=> Enable Dependabot to automate dependency updates

Build/UpdateVersion.ps1, OfficeIMO.Examples/OfficeIMO.Examples.csproj, OfficeIMO.Excel/OfficeIMO.Excel.csproj, OfficeIMO.Word/OfficeIMO.Word.csproj
* Updated the `VersionPrefix` in project files for `OfficeIMO.Excel`, `OfficeIMO.Word`, and `OfficeIMO.Examples`.
* Changed the version in `UpdateVersion.ps1` to reflect the new versioning.
=> chore: 🚀 update version prefix to `1.0.0`

Docs/Examples/ExamplesContentControls/README.MD, OfficeIMO.Examples/Word/ComboBoxes/ComboBoxes.Basic.cs, OfficeIMO.Examples/Word/PictureControls/PictureControls.Basic.cs, OfficeIMO.Examples/Word/RepeatingSections/RepeatingSections.Basic.cs, OfficeIMO.Tests/Word.ComboBox.cs, OfficeIMO.Tests/Word.PictureControl.cs, OfficeIMO.Tests/Word.RepeatingSection.cs, OfficeIMO.Word/WordComboBox.cs, OfficeIMO.Word/WordDocument.PublicMethods.cs, OfficeIMO.Word/WordDocument.cs, OfficeIMO.Word/WordHeaderFooter.Properties.cs, OfficeIMO.Word/WordParagraph.PublicMethods.cs, OfficeIMO.Word/WordParagraph.cs, OfficeIMO.Word/WordPictureControl.cs, OfficeIMO.Word/WordRepeatingSection.cs, OfficeIMO.Word/WordSection.cs, OfficeIMO.Word/WordTable.Properties.cs, README.md
This pull request introduces new features for handling combo box controls, picture controls, and repeating section controls in Word documents. It includes methods for creating, retrieving, and managing these controls, as well as adding corresponding examples and unit tests. Below is a summary of the most important changes grouped by theme:
* Added support for combo box controls, including methods to create, retrieve by alias or tag, and remove them (`OfficeIMO.Word/WordComboBox.cs`, `OfficeIMO.Word/WordDocument.PublicMethods.cs`). [[1]](diffhunk://#diff-6691d22cd73c880d7d785a6d37c39d86fd5e6b00ddfafa9dfcdb038506eb8a8eR1-R69) [[2]](diffhunk://#diff-e577ba03277041388500f0977c2d71c115624ff28c8713f00ba2148ba599b219R643-R684)
* Introduced methods for creating and managing picture controls and …
=> Add repeating section content control
