CHANGELOG.MD
OfficeIMO.Tests/Word.PageSettings.cs
OfficeIMO.Word/WordPageSizes.cs

This PR fixes a problem when the page would be in landscape mode and a comparison of page sizes was made.

Page orientation landscape

---

OfficeIMO.Tests/Word.Save.cs
OfficeIMO.Word/WordDocument.cs

Implement Save and Load to/from Stream

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/Watermark/Watermark.Sample1.cs
OfficeIMO.Examples/Word/Watermark/Watermark.Sample2.cs
OfficeIMO.Tests/Word.Watermark.cs
OfficeIMO.Word/WordWatermark.cs

This PR fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/27

Fixes watermark throwing when Headers aren't added first

---

OfficeIMO.Examples/Word/Lists/Lists.Create2.cs
OfficeIMO.Tests/Word.Lists.cs
OfficeIMO.Tests/Word.Save.cs
OfficeIMO.Word/WordDocument.PrivateMethods.cs
OfficeIMO.Word/WordDocument.cs
OfficeIMO.Word/WordSection.PrivateMethods.cs

Fix not saving list when save to Stream

---

OfficeIMO.Examples/Word/HeadersAndFooters/HeadersAndFooters.Sections1.cs
OfficeIMO.Word/WordBookmark.cs
OfficeIMO.Word/WordParagraph.PrivateMethods.cs

Fixes an issue:
- https://github.com/EvotecIT/OfficeIMO/issues/66

Fixes adding bookmark on document

---

OfficeIMO.Tests/Word.Tables.cs
OfficeIMO.Word/WordTableCell.cs

This PR adds:
- Add AddParagraph() and AddParagraph(string text) to TableCell

Add AddParagraph() and AddParagraph(string text) to TableCell

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/Fields/Fields.cs
OfficeIMO.Examples/Word/Fields/Fields02.cs

This PR adds additional example for Fields

Add additional example for Fields

---

OfficeIMO.Word/WordCustomProperty.cs

This PR resolves the following:
- https://github.com/EvotecIT/OfficeIMO/issues/130

Addd additional custom properties handling

---

OfficeIMO.Tests/Word.Tables.cs
OfficeIMO.Word/WordTable.cs
OfficeIMO.Word/WordTableCell.cs

AddRow functions return the created rows and table cell VerticalAlignment property

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/HyperLinksAndFields/HyperLinks.InTables.cs
OfficeIMO.Tests/Word.Hyperlinks.cs
OfficeIMO.Word/OfficeIMO.Word.csproj
OfficeIMO.Word/WordHyperLink.cs
OfficeIMO.Word/WordParagraph.cs
OfficeIMO.Word/WordSection.cs

This PR fixes:
- https://github.com/EvotecIT/OfficeIMO/issues/156

Add Hyperlink inside table cell

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/SaveToStream/StreamDocumentProperties.Create.cs
OfficeIMO.Examples/Word/Stream/StreamDocumentProperties.Create.cs
OfficeIMO.Tests/Word.Save.cs
OfficeIMO.Word/WordDocument.cs

This PR resolves following issue
- https://github.com/EvotecIT/OfficeIMO/issues/158

Fixes saving properties when using Stream

---

OfficeIMO.Examples/Word/Charts/Charts.cs
OfficeIMO.Tests/Word.Charts.cs
OfficeIMO.Word/WordAreaChart.cs
OfficeIMO.Word/WordBarChart.cs
OfficeIMO.Word/WordChart.PublicMethods.cs
OfficeIMO.Word/WordChart.cs
OfficeIMO.Word/WordDocument.PublicMethods.cs
OfficeIMO.Word/WordLineChart.cs
OfficeIMO.Word/WordParagraph.PublicMethods.cs
OfficeIMO.Word/WordPieChart.cs

It seems lack the area chat ,so I add this type.

Add Areachat

---

OfficeIMO.Word/WordParagraph.PublicMethods.cs

wrapImageText and description now are described in the comments.

Add descriptions to AddImage parameters to documentation

---

OfficeIMO.Word/WordDocument.PublicMethods.cs
OfficeIMO.Word/WordEmbeddedDocument.cs
OfficeIMO.Word/WordField.cs
OfficeIMO.Word/WordParagraph.PublicMethods.cs
OfficeIMO.Word/WordSettings.cs
OfficeIMO.Word/WordTextBox.cs

Fixes some of the non-critical issues reported  by VS

Fixes some warnings as reported by Visual Studio

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/Lists/Lists.Create8.cs
OfficeIMO.Word/WordListStyle.cs

This PR fixes underlying issue as detected in:
- https://github.com/EvotecIT/OfficeIMO/issues/201

Fixes lists NSID value which prevents lists using correct settings when using same type multiple times

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/Lists/Lists.Create9.cs
OfficeIMO.Tests/Word.Lists.cs
OfficeIMO.Word/WordListStyle.cs

This PR adds more list styles:
- UpperLetterWithDot
- LowerLetterWithDot
- LowerLetterWithBracket
- UpperLetterWithBracket
Maybe more should/will be added. Maybe some rebuild should be done to remove some unnecessary duplicate code.

Add 4 more list types with letters

---

OfficeIMO.Word/WordParagraph.PublicMethods.cs

I have documented most of the public paragraph api in this PR.
While doing this I had a few questions or did not understand the
role some things played so I added comments ending in "?" for
my questions and I left a few fields blank. These questions should
be looked over to guarantee accuracy and these fields should be
looked over to finish the documentation for this file.

Filled in documentation for the public paragraph methods.

---

OfficeIMO.Tests/OfficeIMO.Tests.csproj
OfficeIMO.VerifyTests/OfficeIMO.VerifyTests.csproj
OfficeIMO.Word/OfficeIMO.Word.csproj

Bump test dependencies & version

Bump test dependencies

---

OfficeIMO.Tests/Word.Tables.cs
OfficeIMO.Word/OfficeIMO.Word.csproj
OfficeIMO.Word/WordTable.cs

Resolve issue:
- https://github.com/EvotecIT/OfficeIMO/issues/230
Wrongly implemented before caused wrong behavior.

Fixes wrong implementation of repeat header

---

OfficeIMO.Excel/OfficeIMO.Excel.csproj
OfficeIMO.Word/OfficeIMO.Word.csproj

Bump SixLabors.ImageSharp to 2.1.9

Bump SixLabors.ImageSharp to 2.1.9

---

OfficeIMO.Examples/Program.cs
OfficeIMO.Examples/Word/Lists/Lists.Create10.cs
OfficeIMO.Examples/Word/Lists/Lists.Create11.cs
OfficeIMO.Examples/Word/Lists/Lists.Create12.cs
OfficeIMO.Examples/Word/Lists/Lists.Create8.cs
OfficeIMO.Tests/Word.Lists.cs
OfficeIMO.Tests/Word.TOC.cs
OfficeIMO.Word/WordList.cs

This pull request introduces several new examples for working with lists in Word documents, improves the handling of list items, and adds a new test to verify list order. The most important changes are summarized below:
* Added three new examples for creating lists in Word documents: `Example_BasicLists10`, `Example_BasicLists11`, and `Example_BasicLists12` in `OfficeIMO.Examples/Word/Lists` directory. These examples demonstrate how to insert lists between paragraphs and ensure proper order of list items. [[1]](diffhunk://#diff-d99974ac91ec0d712d6c38043c9ec2a4f3bb962e72e944595d4f28e41f046331R1-R26) [[2]](diffhunk://#diff-0aab78c2480f865b2af2d91cd7e03daa531edd6194c370ae0e2191207093f253R1-R41) [[3]](diffhunk://#diff-0e82fc03e10c16fe7840bc10ca2b9362faa2e31cb1bab6c5c69374f0ff26d2caR1-R26)
* …

Fixes how lists behave

---

.github/dependabot.yml

* Specify package-ecosystem as "nuget"
* Set directory to "/"
* Configure weekly update schedule
* Limit open pull requests to 10
* Add reviewer "PrzemyslawKlys"
* Include labels "dependencies" and "automated"

chore: 🔧 update Dependabot configuration for NuGet packages
